In [1]:
import numpy as np

In [2]:
row = [1,2,3]
col = [[1],[2],[3]]
row, col

([1, 2, 3], [[1], [2], [3]])

In [3]:
M = [[1,2,3],[4,5,6],[7,8,9]]
M

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
M[0][1]

2

In [5]:
M[:]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
M = np.array(M, dtype=complex)
M

array([[1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j]])

In [17]:
M = np.array(M, dtype=float)
M

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
M[2][2]

9

In [20]:
# fila 1, y todas las columnas
M[1,:]

array([4, 5, 6])

In [22]:
# toda la columna en posicion 0
M[:,0]

array([1, 4, 7])

In [23]:
# Matriz de ceros de n * n
# .zeros((filas, columnas))
np.zeros((5,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [24]:
# Matriz de unos de n * n
# .ones((filas, columnas))
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [26]:
# Genera una diagonal para una matirz N cuadrada en base a la lista pasada por parametro
# .diag(lista)
x = [1,2,3,4]
N = np.diag(x)
N

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [27]:
# pasandole como parametro una matriz, extrae la diagonal de la misma en un vector
np.diag(N)

array([1, 2, 3, 4])

In [28]:
# Devuelve una tupla con la informacion de filas y columnas
# .shape(Matriz || Vector)
np.shape(N)

(4, 4)

In [29]:
# Suma total de la matriz
np.sum(M)

45

In [30]:
# Suma por filas
# axis=0 Eje horizontal de las x
np.sum(M, axis= 0)

array([12, 15, 18])

In [33]:
# Suma por columnas
# axis=1 Eje Vertical de las y
np.sum(M, axis = 1)

array([ 6, 15, 24])

In [34]:
# Producto de todos los elementos
# .prod(Matriz)
np.prod(M)

362880

In [35]:
# Media arimetica
np.mean(M)

5.0

In [36]:
# Media por filas o columnas de acuerdo al eje
# axis=0 Eje horizontal de las x
# axis=1 Eje Vertical de las y
np.mean(M, axis=0)

array([4., 5., 6.])

In [41]:
# Transpuesta de una matriz
M.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [46]:
# Transpuesta de una matriz
M.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [44]:
# Traz de una Matriz
# Suma de los elementos de la diagonal
M.trace()

15

In [47]:
# Suma de matrices
# Deben ser del mismo tamaño

A = np.array([[1,2], [2,0]])
B = np.array([[3,0], [1,4]])
A + B

array([[4, 2],
       [3, 4]])

In [48]:
# Producto de un escalar por una matriz
A = np.array([[1,2], [2,0]])
A * 5

array([[ 5, 10],
       [10,  0]])

In [51]:
# Producto entre matrices (Producto Matricial)
A = np.array([[1,2], [2,0]])
B = np.array([[3,0], [1,4]])

A.dot(B) 

#Nota si se usa A * B se multiplica posicion a posicion como si fuera una suma

array([[5, 8],
       [6, 0]])

In [55]:
# Potencia de una matriz
A = np.array([[1,2], [2,0]])
# .linalg.matrix_power(Matriz, exponente)
np.linalg.matrix_power(A,2) 

array([[5, 2],
       [2, 4]])

In [57]:
# Rango de una matriz
# Rango => numero de filas no nulas de la matriz, desues de haber obtenido la matriz equivalente
A = np.array([[1,2], [2,0]])
np.linalg.matrix_rank(A)

2

In [58]:
# Inversa de una Matriz
A = np.array([[1,2], [2,0]])
np.linalg.inv(A)

array([[ 0.  ,  0.5 ],
       [ 0.5 , -0.25]])

In [59]:
np.linalg.inv(np.array([[1,3,-1],[0,2,3],[-1,0,2]]))

array([[-0.57142857,  0.85714286, -1.57142857],
       [ 0.42857143, -0.14285714,  0.42857143],
       [-0.28571429,  0.42857143, -0.28571429]])

In [2]:
# Inversa de una Matriz
A = np.array([[1,0,-1], [0,-3,5],[2,-2,0]])
np.linalg.inv(A)

array([[ 2.5 ,  0.5 , -0.75],
       [ 2.5 ,  0.5 , -1.25],
       [ 1.5 ,  0.5 , -0.75]])