# Diagonalización

In [2]:
import numpy as np
from numpy import linalg as LA

In [3]:
A = np.array([[2,-2,1],[2,-8,-2],[1,2,2]])
A

array([[ 2, -2,  1],
       [ 2, -8, -2],
       [ 1,  2,  2]])

In [8]:
# Permite generar los valores como los vectores propios de una matriz cuadrada
# devuelve una tupla, 1er valor => valores propios, 2do valor => vectores propios
w, v = LA.eig(A)
w, v

(array([-7.00000000e+00,  3.00000000e+00, -3.64476202e-16]),
 array([[ 2.35702260e-01,  7.07106781e-01, -6.66666667e-01],
        [ 9.42809042e-01,  5.52232230e-18, -3.33333333e-01],
        [-2.35702260e-01,  7.07106781e-01,  6.66666667e-01]]))

In [6]:
# Primer valor propio de la matriz
L1 = w[0]
L1

-7.000000000000004

In [12]:
# Primer vector propio (columna) de la matriz para el primer valor propio
V1 = v[:,0]
V1

array([ 0.23570226,  0.94280904, -0.23570226])

### Comprobando las propiedades de la diagonalizacion

In [14]:
# Producto matricial de A por V1
np.dot(A, V1)

array([-1.64991582, -6.59966329,  1.64991582])

In [15]:
# Valor propio 1 * vector propio 1  
L1 * V1

array([-1.64991582, -6.59966329,  1.64991582])

In [16]:
# Se comprueba que se obtiene el mismo resultado

In [17]:
# Hacemos la compracacion copn is close, que aproxima los decimales y valida posicion a posicion de cada vector
np.isclose(np.dot(A, V1), L1 * V1)

array([ True,  True,  True])