# Descomponer matrices

encontrar dos o más matrices que me ayuden a escribir la matriz original y que tengan ciertas propiedades

In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.array([[3,2],[4,1]])
A

array([[3, 2],
       [4, 1]])

In [3]:
autovalores, autovectores = np.linalg.eig(A)
print(autovalores)
print("----------")
print(autovectores)

[ 5. -1.]
----------
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [6]:
A_calc = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))
A_calc
# Se obtiene la misma matriz original

array([[3., 2.],
       [4., 1.]])

### Otro ejemplo con una Matriz simetrica (Al trasponer es el mismo resultado a la original)

In [7]:
A_simetrica = np.array([[3,2],[2,3]])
A_simetrica

array([[3, 2],
       [2, 3]])

In [8]:
# Verificando que si sea simetrica a la traspuesta
A_simetrica == A_simetrica.T

array([[ True,  True],
       [ True,  True]])

In [9]:
autovalores, autovectores = np.linalg.eig(A_simetrica)
print(autovalores)
print("----------")
print(autovectores)

[5. 1.]
----------
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [11]:
# Se obtiene la matriz original por otra forma, descomponiendola y no usando la inversa que comuptacionalmente es mas costoso
A_simetrica_calculada = autovectores.dot(np.diag(autovalores)).dot(autovectores.T)
A_simetrica_calculada

array([[3., 2.],
       [2., 3.]])

# Descomposicion de Matriz no cuadrada


In [13]:
A_no_cuadrada = np.array([[1,2,3],[3,4,5]])
A_no_cuadrada

array([[1, 2, 3],
       [3, 4, 5]])

In [15]:
# np.linalg.svd(Matriz no cuadrada)
# Permite calcular los valores no singulares a matrices no cuadradas
U, D, V = np.linalg.svd(A_no_cuadrada)
print(U)
print(D)
print(V)

[[-0.46410668 -0.88577931]
 [-0.88577931  0.46410668]]
[7.97638869 0.61418515]
[[-0.39133557 -0.5605708  -0.72980603]
 [ 0.8247362   0.13817999 -0.54837623]
 [ 0.40824829 -0.81649658  0.40824829]]


In [16]:
np.diag(D)

array([[7.97638869, 0.        ],
       [0.        , 0.61418515]])